version: '3.5'
services:
  config-server-service:
    build: ./
    image: config-server:0.0.2-SNAPSHOT
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./logs:/logs
      - ./basedir:/basedir
      - "/etc/localtime:/etc/localtime:ro"

#use existing network
networks:
  default:
    name: daas-network
    external: true
