scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8888', 'localhost:9000', 'localhost:9001', 'localhost:9002']
        labels:
          application: 'My Spring Boot Application'