version: '3.5'
services:
  monitor-service:
    build: ./
    image: daasalbion/monitor:0.0.2-SNAPSHOT
    container_name: monitor
    ports:
      - "9001:9001"

#use existing network
networks:
  default:
    name: daas-network
    external: true