version: '3'
services:
  user-service:
    build: ./
    container_name: user-service
    image: daasalbion/user-service:0.0.2-SNAPSHOT
    ports:
      - "9004:9004"
    volumes:
      - ./logs:/logs
      - "/etc/localtime:/etc/localtime:ro"
  user-db:
    container_name: user-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: userdb

#use existing network
networks:
  default:
    external:
      name: daas-network